/* ============================================================
   WORLD POOL · WAVE 3 — real-name depth fans actually search.
   All real players ≤ €50M (best-effort June 2026). → M.WORLD
   row = [name, NAT, age, CODE, valueM, fromClub, tags?]
   ============================================================ */
(function () {
  const M = window.MILAN;
  const RS = {
    GK:["GK"], CB:["CB","RCB","LCB"], RB:["RB","RWB"], LB:["LB","LWB"],
    FB:["RB","LB","RWB","LWB"], DM:["DM","RCM","LCM","CM"], CM:["RCM","LCM","CM","DM"],
    AM:["RAM","LAM","RCM"], RW:["RW","RAM"], LW:["LW","LAM"], WF:["RW","LW","RAM","LAM"], ST:["ST"],
  };
  const GRP = { GK:"GK", CB:"DF", RB:"DF", LB:"DF", FB:"DF", DM:"MF", CM:"MF", AM:"MF", RW:"FW", LW:"FW", WF:"FW", ST:"FW" };
  const PART = ["de","di","van","von","el","le","lo","da","dos","del","den","ten","ter"];
  let id = 7000;
  function mk(r){
    const code = r[3];
    const parts = r[0].split(" ");
    let short;
    if (parts.length > 1 && PART.indexOf(parts[parts.length-2].toLowerCase()) !== -1) short = parts.slice(-2).join(" ");
    else short = parts[parts.length-1];
    return { id:"w"+(++id), name:r[0], short, num:((id%30)+1), nat:r[1], age:r[2],
      pos:GRP[code], roles:RS[code], value:r[4], from:r[5], tags:r[6]?r[6].split(","):[], votes:0 };
  }

  const rows = [
    // ===== Lazio =====
    ["Mario Gila","ESP",25,"CB",30,"Lazio"],
    ["Alessio Romagnoli","ITA",31,"CB",18,"Lazio"],
    ["Nuno Tavares","POR",26,"LB",22,"Lazio"],
    ["Manuel Lazzari","ITA",32,"RB",6,"Lazio"],
    ["Adam Marušić","MNE",33,"FB",5,"Lazio"],
    ["Danilo Cataldi","ITA",31,"DM",8,"Lazio"],
    ["Matteo Guendouzi","FRA",27,"CM",30,"Lazio"],
    ["Toma Bašić","CRO",29,"CM",7,"Lazio"],
    ["Fisayo Dele-Bashiru","NGA",25,"CM",16,"Lazio"],
    ["Pedro","ESP",38,"WF",2,"Lazio"],
    ["Tijjani Noslin","NED",27,"WF",12,"Lazio"],
    ["Loum Tchaouna","FRA",22,"RW",16,"Lazio","prospect"],
    ["Ivan Provedel","ITA",32,"GK",10,"Lazio"],
    ["Christos Mandas","GRE",25,"GK",12,"Lazio"],
    // ===== Lecce / younger Serie A CBs =====
    ["Tiago Gabriel","POR",21,"CB",12,"Lecce","prospect"],
    ["Kialonda Gaspar","ANG",24,"CB",8,"Lecce"],
    ["Federico Baschirotto","ITA",29,"CB",10,"Lecce"],
    ["Antonino Gallo","ITA",26,"LB",9,"Lecce"],
    ["Ylber Ramadani","ALB",29,"DM",7,"Lecce"],
    ["Lameck Banda","ZAM",24,"WF",9,"Lecce"],
    ["Nikola Krstović","MNE",26,"ST",22,"Lecce"],
    ["Wladimiro Falcone","ITA",30,"GK",8,"Lecce"],
    // ===== Bologna =====
    ["Sam Beukema","NED",27,"CB",28,"Bologna"],
    ["Jhon Lucumí","COL",27,"CB",28,"Bologna"],
    ["Martin Vitík","CZE",23,"CB",14,"Bologna"],
    ["Charalampos Lykogiannis","GRE",32,"LB",4,"Bologna"],
    ["Emil Holm","SWE",25,"RB",12,"Bologna"],
    ["Lewis Ferguson","SCO",26,"CM",25,"Bologna"],
    ["Remo Freuler","SUI",34,"DM",8,"Bologna"],
    ["Tommaso Pobega","ITA",26,"CM",12,"Bologna"],
    ["Riccardo Orsolini","ITA",29,"RW",30,"Bologna"],
    ["Dan Ndoye","SUI",25,"WF",30,"Bologna"],
    ["Jens Odgaard","DEN",26,"WF",16,"Bologna"],
    ["Thijs Dallinga","NED",25,"ST",18,"Bologna"],
    ["Łukasz Skorupski","POL",35,"GK",4,"Bologna"],
    // ===== Fiorentina =====
    ["Pietro Comuzzo","ITA",21,"CB",25,"Fiorentina","prospect"],
    ["Luca Ranieri","ITA",26,"CB",14,"Fiorentina"],
    ["Marin Pongračić","CRO",28,"CB",16,"Fiorentina"],
    ["Robin Gosens","GER",31,"LB",12,"Fiorentina"],
    ["Dodô","BRA",27,"RB",22,"Fiorentina"],
    ["Rolando Mandragora","ITA",28,"CM",10,"Fiorentina"],
    ["Yacine Adli","FRA",25,"CM",14,"Fiorentina"],
    ["Danilo Cataldi","ITA",31,"DM",8,"Fiorentina"],
    ["Nicolò Fagioli","ITA",25,"CM",22,"Fiorentina"],
    ["Riccardo Sottil","ITA",27,"WF",10,"Fiorentina"],
    ["Moise Kean","ITA",26,"ST",45,"Fiorentina"],
    ["Lucas Beltrán","ARG",25,"ST",16,"Fiorentina"],
    // ===== Torino / Udinese / Genoa / Como =====
    ["Saul Coco","EQG",26,"CB",16,"Torino"],
    ["Guillermo Maripán","CHI",31,"CB",8,"Torino"],
    ["Ivan Ilić","SRB",25,"CM",18,"Torino"],
    ["Vanja Milinković-Savić","SRB",29,"GK",18,"Torino"],
    ["Che Adams","SCO",29,"ST",12,"Torino"],
    ["Lorenzo Lucca","ITA",25,"ST",22,"Udinese"],
    ["Lautaro Giannetti","ARG",32,"CB",4,"Udinese"],
    ["Jaka Bijol","SVN",26,"CB",18,"Udinese"],
    ["Sandi Lovrić","SVN",27,"CM",14,"Udinese"],
    ["Florian Thauvin","FRA",33,"WF",6,"Udinese"],
    ["Morten Thorsby","NOR",29,"CM",6,"Genoa"],
    ["Koni De Winter","BEL",23,"CB",20,"Genoa","prospect"],
    ["Morten Frendrup","DEN",24,"DM",18,"Genoa"],
    ["Ruslan Malinovskyi","UKR",32,"AM",10,"Genoa"],
    ["Andrea Pinamonti","ITA",26,"ST",18,"Genoa"],
    ["Nico Paz","ARG",21,"AM",70,"Como","prospect"],
    ["Sergi Roberto","ESP",34,"CM",3,"Como"],
    ["Alberto Moreno","ESP",33,"LB",2,"Como"],
    ["Patrick Cutrone","ITA",28,"ST",8,"Como"],
    ["Jean Butez","FRA",30,"GK",6,"Como"],
    // ===== Real Madrid / Barça / Atleti fringe =====
    ["Dani Ceballos","ESP",29,"CM",18,"Real Madrid"],
    ["Lucas Vázquez","ESP",34,"RB",4,"Real Madrid"],
    ["Fran García","ESP",26,"LB",18,"Real Madrid"],
    ["Endrick","BRA",19,"ST",40,"Real Madrid","prospect"],
    ["Ferland Mendy","FRA",30,"LB",20,"Real Madrid"],
    ["Andriy Lunin","UKR",27,"GK",22,"Real Madrid"],
    ["Iñaki Peña","ESP",27,"GK",8,"Barcelona"],
    ["Marc Casadó","ESP",22,"DM",30,"Barcelona","prospect"],
    ["Fermín López","ESP",23,"AM",40,"Barcelona","prospect"],
    ["Andreas Christensen","DEN",30,"CB",15,"Barcelona"],
    ["Iñigo Martínez","ESP",35,"CB",4,"Barcelona"],
    ["Eric García","ESP",25,"CB",18,"Barcelona"],
    ["Héctor Fort","ESP",19,"RB",12,"Barcelona","prospect"],
    ["Pablo Barrios","ESP",23,"CM",40,"Atlético","prospect"],
    ["Rodrigo De Paul","ARG",32,"CM",18,"Atlético"],
    ["José María Giménez","URU",31,"CB",20,"Atlético"],
    ["Robin Le Normand","ESP",29,"CB",35,"Atlético"],
    ["Nahuel Molina","ARG",28,"RB",22,"Atlético"],
    ["César Azpilicueta","ESP",36,"FB",2,"Atlético"],
    ["Axel Witsel","BEL",37,"CB",2,"Atlético"],
    ["Jan Oblak","SVN",33,"GK",25,"Atlético"],
    // ===== Other LaLiga =====
    ["Aleix García","ESP",28,"DM",28,"Real Sociedad"],
    ["Martín Zubimendi","ESP",27,"DM",50,"Real Sociedad"],
    ["Igor Zubeldia","ESP",28,"CB",18,"Real Sociedad"],
    ["Hamari Traoré","MLI",33,"RB",4,"Real Sociedad"],
    ["Sergio Gómez","ESP",25,"LB",14,"Real Sociedad"],
    ["Pablo Maffeo","ESP",28,"RB",10,"Mallorca"],
    ["Vedat Muriqi","KOS",31,"ST",10,"Mallorca"],
    ["Antonio Raíllo","ESP",34,"CB",3,"Mallorca"],
    ["Aleix Febas","ESP",29,"CM",6,"Mallorca"],
    ["Álex Baena","ESP",24,"AM",45,"Villarreal"],
    ["Yeremy Pino","ESP",23,"WF",35,"Villarreal","prospect"],
    ["Dani Parejo","ESP",37,"CM",3,"Villarreal"],
    ["Juan Foyth","ARG",28,"FB",22,"Villarreal"],
    ["Logan Costa","TOG",24,"CB",20,"Villarreal"],
    ["Ayoze Pérez","ESP",32,"WF",8,"Villarreal"],
    ["Sergi Cardona","ESP",26,"LB",12,"Villarreal"],
    ["Hugo Duro","ESP",26,"ST",16,"Valencia"],
    ["Pepelu","ESP",27,"DM",14,"Valencia"],
    ["Cristhian Mosquera","ESP",21,"CB",25,"Valencia","prospect"],
    ["Diego López","ESP",24,"WF",18,"Valencia"],
    ["Giuliano Simeone","ARG",23,"WF",24,"Atlético","prospect"],
    ["Antony","BRA",26,"RW",22,"Real Betis"],
    ["Pablo Fornals","ESP",30,"AM",12,"Real Betis"],
    ["Marc Bartra","ESP",35,"CB",2,"Real Betis"],
    ["Aitor Ruibal","ESP",30,"FB",6,"Real Betis"],
    // ===== Premier League depth fans search =====
    ["Joško Gvardiol","CRO",24,"CB",50,"Man City"],
    ["Nico O'Reilly","ENG",20,"FB",22,"Man City","prospect"],
    ["Rico Lewis","ENG",21,"FB",35,"Man City","prospect"],
    ["James McAtee","ENG",23,"AM",30,"Man City","prospect"],
    ["Maxie Aarons","ENG",26,"RB",12,"Bournemouth"],
    ["Lewis Cook","ENG",29,"CM",16,"Bournemouth"],
    ["Justin Kluivert","NED",26,"WF",24,"Bournemouth"],
    ["Marcus Tavernier","ENG",27,"WF",18,"Bournemouth"],
    ["Antoine Semenyo","GHA",26,"WF",45,"Bournemouth"],
    ["Milos Kerkez","HUN",22,"LB",40,"Bournemouth","prospect"],
    ["Illia Zabarnyi","UKR",23,"CB",40,"Bournemouth","prospect"],
    ["Pervis Estupiñán","ECU",28,"LB",24,"Brighton"],
    ["Jan Paul van Hecke","NED",25,"CB",30,"Brighton"],
    ["Carlos Baleba","CMR",22,"DM",50,"Brighton","prospect"],
    ["Kaoru Mitoma","JPN",29,"LW",45,"Brighton"],
    ["Georginio Rutter","FRA",24,"AM",40,"Brighton"],
    ["Danny Welbeck","ENG",35,"ST",6,"Brighton"],
    ["Joël Veltman","NED",34,"FB",4,"Brighton"],
    ["Bart Verbruggen","NED",23,"GK",28,"Brighton","prospect"],
    ["Calvin Bassey","NGA",26,"CB",28,"Fulham"],
    ["Sasa Lukic","SRB",29,"DM",16,"Fulham"],
    ["Emile Smith Rowe","ENG",25,"AM",30,"Fulham"],
    ["Alex Iwobi","NGA",29,"WF",30,"Fulham"],
    ["Raúl Jiménez","MEX",35,"ST",10,"Fulham"],
    ["Bernd Leno","GER",34,"GK",10,"Fulham"],
    // ===== Bundesliga depth =====
    ["Jonathan Tah","GER",30,"CB",30,"Bayern"],
    ["Josip Stanišić","CRO",26,"FB",25,"Bayern"],
    ["Konrad Laimer","AUT",28,"CM",24,"Bayern"],
    ["Aleksandar Pavlović","GER",22,"DM",40,"Bayern","prospect"],
    ["Mathys Tel","FRA",21,"WF",35,"Bayern","prospect"],
    ["Sven Ulreich","GER",37,"GK",2,"Bayern"],
    ["Karim Adeyemi","GER",24,"WF",35,"Dortmund"],
    ["Maximilian Beier","GER",23,"ST",30,"Dortmund","prospect"],
    ["Felix Nmecha","GER",25,"CM",28,"Dortmund"],
    ["Ramy Bensebaini","ALG",31,"FB",14,"Dortmund"],
    ["Yan Couto","BRA",23,"RB",22,"Dortmund","prospect"],
    ["Gregor Kobel","SUI",28,"GK",40,"Dortmund"],
    ["Xavi Simons","NED",23,"AM",50,"RB Leipzig","prospect"],
    ["Benjamin Šeško","SVN",23,"ST",50,"RB Leipzig","prospect"],
    ["Lois Openda","BEL",26,"ST",55,"RB Leipzig"],
    ["Castello Lukeba","FRA",23,"CB",40,"RB Leipzig","prospect"],
    ["Willi Orbán","HUN",33,"CB",8,"RB Leipzig"],
    ["David Raum","GER",28,"LB",28,"RB Leipzig"],
    ["Hugo Larsson","SWE",21,"CM",42,"Frankfurt","prospect"],
    ["Ellyes Skhiri","TUN",31,"DM",12,"Frankfurt"],
    ["Robin Koch","GER",29,"CB",22,"Frankfurt"],
    ["Nathaniel Brown","GER",22,"LB",18,"Frankfurt","prospect"],
    ["Jean-Mattéo Bahoya","FRA",20,"WF",20,"Frankfurt","prospect"],
    // ===== Ligue 1 depth =====
    ["Warren Zaïre-Emery","FRA",20,"CM",50,"PSG","prospect"],
    ["Lucas Beraldo","BRA",22,"CB",25,"PSG","prospect"],
    ["Lucas Hernández","FRA",30,"CB",18,"PSG"],
    ["Gonçalo Ramos","POR",24,"ST",45,"PSG"],
    ["Lee Kang-in","KOR",25,"AM",40,"PSG"],
    ["Senny Mayulu","FRA",19,"AM",22,"PSG","prospect"],
    ["Maghnes Akliouche","FRA",24,"AM",45,"Monaco"],
    ["Folarin Balogun","USA",24,"ST",35,"Monaco"],
    ["Denis Zakaria","SUI",29,"DM",30,"Monaco"],
    ["Soungoutou Magassa","FRA",22,"DM",18,"Monaco","prospect"],
    ["Wilfried Singo","CIV",25,"FB",30,"Monaco"],
    ["Pierre-Emerick Aubameyang","GAB",36,"ST",6,"Marseille"],
    ["Geoffrey Kondogbia","CAF",33,"DM",6,"Marseille"],
    ["Leonardo Balerdi","ARG",27,"CB",25,"Marseille"],
    ["Adrien Rabiot","FRA",31,"CM",20,"Marseille"],
    ["Jonathan Rowe","ENG",22,"WF",18,"Marseille","prospect"],
    ["Hákon Haraldsson","ISL",23,"AM",20,"Lille"],
    ["Edon Zhegrova","KOS",27,"RW",22,"Lille"],
    ["Jonathan David","CAN",26,"ST",45,"Lille"],
    ["Benjamin André","FRA",35,"DM",4,"Lille"],
    ["Lucas Chevalier","FRA",24,"GK",35,"Lille","prospect"],
    // ===== Eredivisie / Portugal / others fans search =====
    ["Luuk de Jong","NED",35,"ST",4,"PSV"],
    ["Joey Veerman","NED",27,"CM",26,"PSV"],
    ["Malik Tillman","USA",23,"AM",30,"PSV","prospect"],
    ["Guus Til","NED",28,"CM",14,"PSV"],
    ["Sergiño Dest","USA",25,"FB",22,"PSV"],
    ["Walter Benítez","ARG",33,"GK",8,"PSV"],
    ["Igor Paixão","BRA",25,"LW",24,"Feyenoord"],
    ["Anis Hadj Moussa","ALG",23,"RW",16,"Feyenoord","prospect"],
    ["In-beom Hwang","KOR",29,"CM",14,"Feyenoord"],
    ["Gernot Trauner","AUT",33,"CB",6,"Feyenoord"],
    ["Wout Weghorst","NED",33,"ST",8,"Ajax"],
    ["Davy Klaassen","NED",33,"CM",6,"Ajax"],
    ["Youri Baas","NED",23,"CB",12,"Ajax","prospect"],
    ["Antony","BRA",26,"RW",22,"Real Betis"],
    ["Georges Mikautadze","GEO",25,"ST",30,"Lyon"],
    ["Rayan Cherki","FRA",22,"AM",40,"Lyon","prospect"],
    ["Nemanja Matić","SRB",37,"DM",3,"Lyon"],
    ["Corentin Tolisso","FRA",31,"CM",10,"Lyon"],
    ["Alexandre Lacazette","FRA",35,"ST",4,"Lyon"],
    // ===== Glasgow / Championship / Turkey extra =====
    ["Reo Hatate","JPN",28,"CM",12,"Celtic"],
    ["Cameron Carter-Vickers","USA",28,"CB",16,"Celtic"],
    ["Daizen Maeda","JPN",28,"WF",14,"Celtic"],
    ["Matt O'Riley","DEN",25,"AM",26,"Brighton"],
    ["Nicolas Kühn","GER",26,"WF",18,"Celtic"],
    ["Mohammed Kudus","GHA",25,"AM",45,"Tottenham"],
    ["Wilfried Gnonto","ITA",22,"WF",22,"Leeds","prospect"],
    ["Largie Ramazani","BEL",25,"WF",14,"Leeds"],
    ["Brenden Aaronson","USA",25,"AM",18,"Leeds"],
    ["Victor Osimhen","NGA",27,"ST",50,"Galatasaray"],
    ["Mauro Icardi","ARG",33,"ST",10,"Galatasaray"],
    ["Hakim Ziyech","MAR",33,"WF",6,"Galatasaray"],
    ["Edin Džeko","BIH",40,"ST",2,"Fenerbahçe"],
    ["Sebastian Szymański","POL",27,"AM",22,"Fenerbahçe"],
    ["İrfan Can Kahveci","TUR",30,"AM",12,"Fenerbahçe"],
  ];

  M.WORLD = (M.WORLD || []).concat(rows.map(mk));
})();
