/* ============================================================
   WORLD POOL · WAVE 2 — deeper squads across every major league.
   All real players ≤ €50M. Concatenated into M.WORLD.
   row = [name, NAT, age, CODE, valueM, fromClub, tags?]
   ============================================================ */
(function () {
  const M = window.MILAN;
  const RS = {
    GK:["GK"], CB:["CB","RCB","LCB"], RB:["RB","RWB"], LB:["LB","LWB"],
    FB:["RB","LB","RWB","LWB"], DM:["DM","RCM","LCM","CM"], CM:["RCM","LCM","CM","DM"],
    AM:["RAM","LAM","RCM"], RW:["RW","RAM"], LW:["LW","LAM"], WF:["RW","LW","RAM","LAM"], ST:["ST"],
  };
  const GRP = { GK:"GK", CB:"DF", RB:"DF", LB:"DF", FB:"DF", DM:"MF", CM:"MF", AM:"MF", RW:"FW", LW:"FW", WF:"FW", ST:"FW" };
  const PART = ["de","di","van","von","el","le","lo","da","dos","del","den","ten","ter"];
  let id = 5000;
  function mk(r){
    const code = r[3];
    const parts = r[0].split(" ");
    let short;
    if (parts.length > 1 && PART.indexOf(parts[parts.length-2].toLowerCase()) !== -1) short = parts.slice(-2).join(" ");
    else short = parts[parts.length-1];
    return { id:"w"+(++id), name:r[0], short, num:((id%30)+1), nat:r[1], age:r[2],
      pos:GRP[code], roles:RS[code], value:r[4], from:r[5], tags:r[6]?r[6].split(","):[], votes:0 };
  }

  const rows = [
    // ===== Premier League depth =====
    ["Jorginho","ITA",34,"DM",5,"Arsenal"],
    ["Oleksandr Zinchenko","UKR",29,"LB",20,"Arsenal"],
    ["Kieran Tierney","SCO",28,"LB",16,"Arsenal"],
    ["Fabio Vieira","POR",25,"AM",18,"Arsenal"],
    ["Jakub Kiwior","POL",26,"CB",28,"Arsenal"],
    ["Reiss Nelson","ENG",26,"WF",12,"Arsenal"],
    ["James McAtee","ENG",23,"AM",35,"Man City","prospect"],
    ["Sergio Gómez","ESP",25,"LB",14,"Man City"],
    ["Máximo Perrone","ARG",23,"CM",16,"Man City"],
    ["Federico Chiesa","ITA",28,"WF",24,"Liverpool"],
    ["Kostas Tsimikas","GRE",30,"LB",12,"Liverpool"],
    ["Caoimhín Kelleher","IRL",27,"GK",18,"Liverpool"],
    ["Tyler Morton","ENG",23,"CM",22,"Liverpool"],
    ["Diogo Dalot","POR",27,"RB",35,"Man Utd"],
    ["Mason Mount","ENG",27,"AM",30,"Man Utd"],
    ["André Onana","CMR",30,"GK",26,"Man Utd"],
    ["Harry Maguire","ENG",33,"CB",10,"Man Utd"],
    ["Victor Lindelöf","SWE",31,"CB",7,"Man Utd"],
    ["Mykhailo Mudryk","UKR",25,"LW",28,"Chelsea"],
    ["João Félix","POR",26,"AM",35,"Chelsea"],
    ["Renato Veiga","POR",23,"CB",35,"Chelsea","prospect"],
    ["Axel Disasi","FRA",28,"CB",24,"Chelsea"],
    ["Rodrigo Bentancur","URU",28,"DM",26,"Tottenham"],
    ["Pape Matar Sarr","SEN",23,"CM",45,"Tottenham"],
    ["Brennan Johnson","WAL",25,"RW",40,"Tottenham"],
    ["Richarlison","BRA",29,"ST",24,"Tottenham"],
    ["Yves Bissouma","MLI",29,"DM",22,"Tottenham"],
    ["Ben Davies","WAL",33,"CB",6,"Tottenham"],
    ["Callum Wilson","ENG",34,"ST",6,"Newcastle"],
    ["Joe Willock","ENG",26,"CM",22,"Newcastle"],
    ["Jacob Murphy","ENG",31,"RW",14,"Newcastle"],
    ["Leon Bailey","JAM",28,"RW",28,"Aston Villa"],
    ["Lucas Digne","FRA",32,"LB",9,"Aston Villa"],
    ["Matty Cash","POL",28,"RB",22,"Aston Villa"],
    ["Boubacar Kamara","FRA",26,"DM",45,"Aston Villa"],
    ["Pau Torres","ESP",29,"CB",35,"Aston Villa"],
    ["Tyrone Mings","ENG",33,"CB",9,"Aston Villa"],
    ["Kaoru Mitoma","JPN",29,"LW",50,"Brighton"],
    ["Carlos Baleba","CMR",22,"DM",50,"Brighton","prospect"],
    ["Jan Paul van Hecke","NED",25,"CB",35,"Brighton"],
    ["Georginio Rutter","FRA",24,"AM",35,"Brighton"],
    ["Yankuba Minteh","GAM",21,"RW",45,"Brighton","prospect"],
    ["Danny Welbeck","ENG",35,"ST",6,"Brighton"],
    ["Andreas Pereira","BRA",30,"AM",18,"Fulham"],
    ["Emile Smith Rowe","ENG",25,"AM",24,"Fulham"],
    ["Alex Iwobi","NGA",30,"WF",26,"Fulham"],
    ["Rodrigo Muniz","BRA",25,"ST",28,"Fulham"],
    ["Antonee Robinson","USA",28,"LB",30,"Fulham"],
    ["Calvin Bassey","NGA",26,"CB",28,"Fulham"],
    ["Bernd Leno","GER",34,"GK",10,"Fulham"],
    ["Antoine Semenyo","GHA",26,"WF",45,"Bournemouth"],
    ["Justin Kluivert","NED",26,"WF",24,"Bournemouth"],
    ["Marcus Tavernier","ENG",27,"WF",18,"Bournemouth"],
    ["Dango Ouattara","BUR",24,"RW",28,"Bournemouth"],
    ["Lewis Cook","ENG",29,"CM",14,"Bournemouth"],
    ["Mikkel Damsgaard","DEN",26,"AM",28,"Brentford"],
    ["Christian Nørgaard","DEN",32,"DM",10,"Brentford"],
    ["Kevin Schade","GER",24,"WF",25,"Brentford"],
    ["Keane Lewis-Potter","ENG",25,"LB",16,"Brentford"],
    ["James Tarkowski","ENG",33,"CB",8,"Everton"],
    ["Jack Harrison","ENG",29,"WF",12,"Everton"],
    ["Idrissa Gueye","SEN",36,"DM",3,"Everton"],
    ["Vitalii Mykolenko","UKR",27,"LB",18,"Everton"],
    ["Abdoulaye Doucouré","MLI",33,"CM",7,"Everton"],
    ["Chris Wood","NZL",34,"ST",7,"Nottm Forest"],
    ["Nicolás Domínguez","ARG",28,"CM",16,"Nottm Forest"],
    ["Ola Aina","NGA",29,"RB",18,"Nottm Forest"],
    ["Ibrahim Sangaré","CIV",28,"DM",24,"Nottm Forest"],
    ["Callum Hudson-Odoi","ENG",25,"WF",25,"Nottm Forest"],
    ["Matz Sels","BEL",34,"GK",10,"Nottm Forest"],
    ["Wilfried Gnonto","ITA",22,"WF",28,"Leeds"],
    ["Daniel James","WAL",28,"WF",12,"Leeds"],
    ["Ethan Ampadu","WAL",25,"DM",22,"Leeds"],
    ["Pascal Struijk","NED",26,"CB",22,"Leeds"],
    ["Brenden Aaronson","USA",25,"AM",16,"Leeds"],
    ["Illan Meslier","FRA",26,"GK",16,"Leeds"],
    ["Joel Piroe","NED",26,"ST",18,"Leeds"],
    ["Dan Neil","ENG",24,"CM",16,"Sunderland"],
    ["Chris Rigg","ENG",18,"CM",25,"Sunderland","prospect"],
    ["Wilson Isidor","FRA",25,"ST",14,"Sunderland"],
    // ===== Serie A depth =====
    ["Nicolò Fagioli","ITA",25,"CM",26,"Juventus"],
    ["Timothy Weah","USA",26,"RW",22,"Juventus"],
    ["Daniele Rugani","ITA",32,"CB",6,"Juventus"],
    ["Kenan Yıldız","TUR",21,"AM",85,"Juventus","prospect"],
    ["Jonathan David","CAN",26,"ST",40,"Juventus"],
    ["Federico Dimarco","ITA",28,"LB",45,"Inter"],
    ["Denzel Dumfries","NED",30,"RB",30,"Inter"],
    ["Kristjan Asllani","ALB",24,"DM",20,"Inter"],
    ["Piotr Zieliński","POL",32,"CM",14,"Inter"],
    ["Benjamin Pavard","FRA",30,"CB",30,"Inter"],
    ["Stanislav Lobotka","SVK",31,"DM",30,"Napoli"],
    ["Alessandro Buongiorno","ITA",27,"CB",40,"Napoli"],
    ["Giacomo Raspadori","ITA",26,"ST",26,"Napoli"],
    ["Billy Gilmour","SCO",25,"CM",18,"Napoli"],
    ["Mathías Olivera","URU",28,"LB",22,"Napoli"],
    ["David Neres","BRA",29,"WF",35,"Napoli"],
    ["Paulo Dybala","ARG",32,"AM",18,"Roma"],
    ["Evan Ndicka","CIV",26,"CB",35,"Roma"],
    ["Mile Svilar","SRB",26,"GK",30,"Roma"],
    ["Tommaso Baldanzi","ITA",23,"AM",16,"Roma"],
    ["Nicola Zalewski","POL",24,"FB",16,"Roma"],
    ["Taty Castellanos","ARG",27,"ST",26,"Lazio"],
    ["Matteo Guendouzi","FRA",27,"CM",30,"Lazio"],
    ["Pedro","ESP",38,"WF",3,"Lazio"],
    ["Gianluca Scamacca","ITA",27,"ST",32,"Atalanta"],
    ["Berat Djimsiti","ALB",32,"CB",8,"Atalanta"],
    ["Davide Zappacosta","ITA",33,"FB",7,"Atalanta"],
    ["Mario Pašalić","CRO",31,"CM",14,"Atalanta"],
    ["Rolando Mandragora","ITA",28,"CM",14,"Fiorentina"],
    ["Lucas Beltrán","ARG",25,"ST",18,"Fiorentina"],
    ["Dodô","BRA",27,"RB",28,"Fiorentina"],
    ["Riccardo Orsolini","ITA",29,"RW",30,"Bologna"],
    ["Lewis Ferguson","SCO",27,"CM",30,"Bologna"],
    ["Dan Ndoye","SUI",25,"RW",32,"Bologna"],
    ["Sam Beukema","NED",27,"CB",25,"Bologna"],
    ["Jhon Lucumí","COL",28,"CB",22,"Bologna"],
    ["Raoul Bellanova","ITA",26,"RB",28,"Torino"],
    ["Duván Zapata","COL",35,"ST",5,"Torino"],
    ["Jaka Bijol","SVN",27,"CB",22,"Udinese"],
    ["Sandi Lovrić","SVN",27,"CM",14,"Udinese"],
    ["Morten Frendrup","DEN",25,"DM",18,"Genoa"],
    ["Ruslan Malinovskyi","UKR",33,"AM",8,"Genoa"],
    ["Koni De Winter","BEL",24,"CB",25,"Genoa"],
    ["Nico Paz","ARG",21,"AM",70,"Como","prospect"],
    ["Sergi Roberto","ESP",34,"CM",2,"Como"],
    ["Patrick Cutrone","ITA",28,"ST",8,"Como"],
    ["Roberto Piccoli","ITA",25,"ST",16,"Cagliari"],
    ["Răzvan Marin","ROU",30,"CM",8,"Cagliari"],
    ["Domenico Berardi","ITA",31,"WF",14,"Sassuolo"],
    ["Armand Laurienté","FRA",27,"LW",18,"Sassuolo"],
    ["Adrián Bernabé","ESP",24,"CM",14,"Parma"],
    // ===== La Liga depth =====
    ["Dani Ceballos","ESP",29,"CM",16,"Real Madrid"],
    ["Ferland Mendy","FRA",30,"LB",25,"Real Madrid"],
    ["Lucas Vázquez","ESP",34,"RB",4,"Real Madrid"],
    ["Fermín López","ESP",22,"AM",50,"Barcelona","prospect"],
    ["Andreas Christensen","DEN",29,"CB",18,"Barcelona"],
    ["Iñigo Martínez","ESP",34,"CB",8,"Barcelona"],
    ["Conor Gallagher","ENG",26,"CM",35,"Atlético"],
    ["Giuliano Simeone","ARG",23,"RW",30,"Atlético"],
    ["Pablo Barrios","ESP",22,"CM",45,"Atlético","prospect"],
    ["Igor Zubeldia","ESP",28,"CB",25,"Real Sociedad"],
    ["Nico Williams","ESP",23,"LW",50,"Athletic Club"],
    ["Unai Simón","ESP",28,"GK",30,"Athletic Club"],
    ["Aitor Ruibal","ESP",29,"WF",10,"Real Betis"],
    ["Marc Roca","ESP",29,"DM",12,"Real Betis"],
    ["Álex Baena","ESP",24,"AM",45,"Villarreal"],
    ["Yeremy Pino","ESP",23,"RW",35,"Villarreal"],
    ["Gerard Moreno","ESP",34,"ST",8,"Villarreal"],
    ["Hugo Duro","ESP",26,"ST",18,"Valencia"],
    ["Pepelu","ESP",27,"DM",18,"Valencia"],
    ["Dodi Lukébakio","COD",28,"WF",22,"Sevilla"],
    ["Loïc Badé","FRA",26,"CB",30,"Sevilla"],
    ["Borja Iglesias","ESP",33,"ST",8,"Celta"],
    // ===== Bundesliga depth =====
    ["Karim Adeyemi","GER",24,"WF",40,"Dortmund"],
    ["Felix Nmecha","GER",25,"CM",30,"Dortmund"],
    ["Niklas Süle","GER",30,"CB",18,"Dortmund"],
    ["Gregor Kobel","SUI",28,"GK",40,"Dortmund"],
    ["Maximilian Beier","GER",23,"ST",30,"Dortmund"],
    ["Joshua Kimmich","GER",31,"DM",45,"Bayern"],
    ["Sacha Boey","FRA",25,"RB",20,"Bayern"],
    ["Patrik Schick","CZE",30,"ST",30,"Leverkusen"],
    ["Aleix García","ESP",28,"DM",30,"Leverkusen"],
    ["Robert Andrich","GER",31,"DM",18,"Leverkusen"],
    ["Xavi Simons","NED",23,"AM",50,"RB Leipzig"],
    ["Lutsharel Geertruida","NED",26,"FB",30,"RB Leipzig"],
    ["Mario Götze","GER",34,"AM",6,"Frankfurt"],
    ["Robin Koch","GER",30,"CB",18,"Frankfurt"],
    ["Ermedin Demirović","BIH",28,"ST",22,"Stuttgart"],
    ["Marvin Ducksch","GER",32,"ST",10,"Werder Bremen"],
    // ===== Ligue 1 depth =====
    ["Lucas Hernández","FRA",30,"CB",20,"PSG"],
    ["Marquinhos","BRA",32,"CB",30,"PSG"],
    ["Pierre-Emile Højbjerg","DEN",30,"DM",22,"Marseille"],
    ["Leonardo Balerdi","ARG",27,"CB",30,"Marseille"],
    ["Geoffrey Kondogbia","CTA",33,"DM",6,"Marseille"],
    ["Denis Zakaria","SUI",29,"DM",30,"Monaco"],
    ["Folarin Balogun","USA",24,"ST",35,"Monaco"],
    ["Corentin Tolisso","FRA",31,"CM",10,"Lyon"],
    ["Nicolás Tagliafico","ARG",33,"LB",6,"Lyon"],
    ["Edon Zhegrova","KVX",27,"RW",28,"Lille"],
    ["Benjamin André","FRA",35,"DM",4,"Lille"],
    ["Przemysław Frankowski","POL",31,"FB",10,"Lens"],
    ["Andy Diouf","FRA",23,"CM",22,"Lens"],
    ["Ludovic Blas","FRA",28,"AM",16,"Rennes"],
    // ===== Eredivisie / Primeira / Championship / others =====
    ["Davy Klaassen","NED",33,"CM",6,"Ajax"],
    ["Wout Weghorst","NED",33,"ST",8,"Ajax"],
    ["Joey Veerman","NED",27,"CM",24,"PSV"],
    ["Guus Til","NED",28,"AM",14,"PSV"],
    ["Ivan Perišić","CRO",37,"WF",4,"PSV"],
    ["Anis Hadj Moussa","ALG",23,"RW",18,"Feyenoord"],
    ["In-beom Hwang","KOR",29,"CM",14,"Feyenoord"],
    ["Sem Steijn","NED",24,"AM",20,"Feyenoord"],
    ["António Silva","POR",22,"CB",50,"Benfica","prospect"],
    ["Fredrik Aursnes","NOR",30,"CM",25,"Benfica"],
    ["Alan Varela","ARG",24,"DM",35,"Porto"],
    ["Geny Catamo","MOZ",25,"RW",18,"Sporting CP"],
    ["Mauro Icardi","ARG",33,"ST",10,"Galatasaray"],
    ["Youssef En-Nesyri","MAR",29,"ST",25,"Fenerbahçe"],
    ["Sebastian Szymański","POL",27,"AM",22,"Fenerbahçe"],
    ["Wilfred Ndidi","NGA",29,"DM",18,"Leicester"],
    ["Conor Coady","ENG",33,"CB",6,"Leicester"],
    ["Tyler Dibling","ENG",20,"WF",35,"Southampton","prospect"],
  ];

  M.WORLD = (M.WORLD || []).concat(rows.map(mk));
})();
